### ISSUE TITLE
Need to upload final version on the day

### ISSUE THREAD

**Issue by Jimbles** [Jimbles/RPi_Photobooth#3]
Made last minute changes, still only on SD card on pi

**Comment by iroQuai** [comment]
Please do! Of all the forks from drumminhands this version is by far the most interesting for me

**Comment by Jimbles** [comment]
Done, and thanks for the interest in this! It was only small changes. I stopped it uploading to twitter immediately, we had a shaky internet connection so it would take too long for people to see the results. It now just uploads in the background as part of the idle process.

**Comment by iroQuai** [comment]
Thanks for uploading! Uploading in the background seems like a good idea :)
