### ISSUE TITLE
Wiring diagram?

### ISSUE THREAD

**Issue by iroQuai** [Jimbles/RPi_Photobooth#4]
Do you have a wiring diagram available maybe? Although most forks still depend on the original wiring of drumminhands_photobooth, this one is different. One LED less, and different functions for each LED?

Hope you can help me!

**Comment by iroQuai** [comment]
No need anymore, it was very easy just to read the gpio numbers out of the code :)
(sorry this is my first Raspberry Pi project! bit of a noob still...)

**Comment by Jimbles** [comment]
No worries! I used a darlington array for some of them as I ended up using a few LEDs controlled from a single pin. like [this](http://www.petervis.com/Raspberry_PI/Raspberry_Pi_GPIO_Header/Raspberry_Pi_GPIO_Header_Pin_Interfacing.html)
