### ISSUE TITLE
Tumblr uploading?

### ISSUE THREAD

**Issue by iroQuai** [Jimbles/RPi_Photobooth#5]
Although the config file still asks for the oath-keys for tumblr, it seems like you've removed this functionality completely in the main code... am i right, or am i missing something? And second: is it difficult to put this back in for a coding noob like me? Since youve edited quite a lot, i guess it probably isn't as simple as just copy-pasting the tumblr-part of the original code?

**Comment by Jimbles** [comment]
You are correct, I took out all the tumblr stuff. But you could add it back in or replace the twitter upload wih tumblr pretty easily. in the function `tweet_pics`, you could replace the lines using the twitter api, with those from the orginal which use the tumblr api instead:
```
				file_to_upload = config.file_path + now + ".gif"
				client.create_photo(config.tumblr_blog, state="published", tags=["drumminhandsPhotoBooth"], data=file_to_upload)
```

**Comment by iroQuai** [comment]
too long since i've checked this project! finaly found the time to play with it some more...
thanks for the help!
