### ISSUE TITLE
LED in "start-button"

### ISSUE THREAD

**Issue by iroQuai** [Jimbles/RPi_Photobooth#6]
Hi there!
I have a 'start' button with a LED embedded. I believe in your setup there wasn't. I'm trying to make that button on when idle and off when in proces. I tried to edit the photobooth.py, but this is litterly my first attempt in writing/editting python, so probably i'm overseeing something very simple.

Could you tell me how to add this funciton, or review my code to see what i did wrong? 
thanks a milion in advance!!!

ps 
Here is my attempt: https://github.com/iroQuai/Gifmenger/edit/master/photobooth.py
what i did was 
- I added `idle_led_pin = 12 #` under "GPIO Config"
- copied and editted a line under functions 'def led_init()', 'def led_all_off' and 'def led_all_on' 
- added 'GPIO.output(idle_led_pin, True)' "def start_photobooth(self):" (just above step 1)
- added 'GPIO.output(idle_led_pin, False)' just below the beginning of step 1...

**Comment by iroQuai** [comment]
Sorry wrong link... To view the code (including my changes) I guess this is the appropriate link: https://github.com/iroQuai/Gifmenger/blob/master/photobooth.py

**Comment by Jimbles** [comment]
hey! I actually did have this functionality in place but I turned it off! The lines `  #GPIO.output(photo_indicator_pin, False)` etc.  have been commented out, but if you uncomment them. These are at lines 428 541and 611. 

However, your description of what to change is correct!

**Comment by iroQuai** [comment]
I realised what i did wrong! I mixed up physical pinout and gpio pinout! thats why my setup didn't work...
I rewired everything and used your built in functionality. Thanks for your quick reply :)

**Comment by Jimbles** [comment]
no problem. glad you got it sorted!
